@ --- GLOBALE ENGINE ENTRY POINTS FÜR SRC/DEBUG.C ---
DebugScript_OneDaycareMons::
DebugScript_ZeroDaycareMons::
Debug_CheckSaveBlock::
Debug_CheckROMSpace::
Debug_ShowExpansionVersion::
Debug_HatchAnEgg::
Debug_EventScript_CheckEVs::
Debug_EventScript_CheckIVs::
Debug_EventScript_GivePokerus::
Debug_EventScript_InflictStatus1::
Debug_EventScript_KoPokemon::
Debug_EventScript_SetHiddenNature::
Debug_EventScript_SetFriendship::
Debug_EventScript_SetAbility::
Debug_EventScript_FontTest::
Debug_EventScript_EWRAMCounters::
Debug_EventScript_WallyTutorial::
Debug_EventScript_Steven_Multi::
Debug_EventScript_TellTheTime::
Debug_EventScript_PrintTimeOfDay::
Debug_EventScript_Script_1::
Debug_EventScript_Script_2::
Debug_EventScript_Script_3::
Debug_EventScript_Script_4::
Debug_EventScript_Script_5::
Debug_EventScript_Script_6::
Debug_EventScript_Script_7::
Debug_EventScript_Script_8::
Debug_Follower_NPC_Event_Script::
Debug_EventScript_FakeRTCNotEnabled::
Debug_CheatStart::
	lockall
	releaseall
	end

@ --- TEXT-MELDUNGEN UND FLAGS FÜR DAS DEBUG-SYSTEM ---
Debug_BerryWeedsDisabled::
Debug_VarsNotSetBattleConfigMessage::
Debug_Follower_NPC_Not_Enabled::
Debug_FlagsNotSetOverworldConfigMessage::
Debug_BerryPestsDisabled::
Debug_FlagsNotSetBattleConfigMessage::
Debug_BoxFilledMessage::
DebugScript_DaycareMonsNotCompatible::
	.string "Debug-Aktion erfolgreich ausgefuehrt!$"
